### ISSUE TITLE
app shows no processes or system info in GUI, Rust panic on command line

### ISSUE THREAD

**Issue by ThinkerDreamer** [nokyan/resources#14] opened 2023-10-13 22:21 UTC
Hello! I'm on Mint 21.2, here's my system info. 
<html><details><summary>Details</summary>
<pre>
System:
  Kernel: 5.15.0-86-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Micro-Star product: GF63 Thin 9SC v: REV:1.0 serial: <superuser required>
    Chassis: type: 10 serial: <superuser required>
  Mobo: Micro-Star model: MS-16R3 v: REV:1.0 serial: <superuser required>
    UEFI: American Megatrends v: E16R3IMS.108 date: 03/26/2020
Battery:
  ID-1: BAT1 charge: 30.8 Wh (64.8%) condition: 47.5/51.3 Wh (92.5%) volts: 11.2 min: 11.4
    model: MSI Corp. MS-16R3 serial: N/A status: Discharging
CPU:
  Info: quad core model: Intel Core i5-9300H bits: 64 type: MT MCP arch: Coffee Lake rev: A cache:
    L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 854 high: 900 min/max: 800/4100 cores: 1: 832 2: 882 3: 872 4: 856 5: 800
    6: 900 7: 800 8: 891 bogomips: 38400
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] vendor: Micro-Star MSI driver: i915
    v: kernel ports: active: eDP-1 empty: DP-1,HDMI-A-1,HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:3e9b
  Device-2: NVIDIA TU117M [GeForce GTX 1650 Mobile / Max-Q] vendor: Micro-Star MSI
    driver: nvidia v: 535.86.05 pcie: speed: 5 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:1f91
  Device-3: Acer HD Webcam type: USB driver: uvcvideo bus-ID: 1-11:2 chip-ID: 5986:211b
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting,nvidia
    unloaded: fbdev,nouveau,vesa gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 102
  Monitor-1: eDP-1-1 mapped: eDP-1 model: AU Optronics res: 1920x1080 dpi: 142
    diag: 394mm (15.5")
  OpenGL: renderer: NVIDIA GeForce GTX 1650 with Max-Q Design/PCIe/SSE2
    v: 4.6.0 NVIDIA 535.86.05 direct render: Yes
Audio:
  Device-1: Intel Cannon Lake PCH cAVS vendor: Micro-Star MSI driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:a348
  Sound Server-1: ALSA v: k5.15.0-86-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Cannon Lake PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:a370
  IF: wlo1 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: 3000 bus-ID: 03:00.0
    chip-ID: 10ec:8168
  IF: enp3s0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel Bluetooth 9460/9560 Jefferson Peak (JfP) type: USB driver: btusb v: 0.8
    bus-ID: 1-14:3 chip-ID: 8087:0aaa
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 3.0 lmp-v: 5.1
    sub-v: 100
Drives:
  Local Storage: total: 476.94 GiB used: 183.37 GiB (38.4%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: PC SN520 SDAPNUW-512G-1032 size: 476.94 GiB
    speed: 15.8 Gb/s lanes: 2 serial: <filter> temp: 48.9 C
Partition:
  ID-1: / size: 68.2 GiB used: 23.45 GiB (34.4%) fs: ext4 dev: /dev/nvme0n1p7
  ID-2: /boot/efi size: 296 MiB used: 35.8 MiB (12.1%) fs: vfat dev: /dev/nvme0n1p1
  ID-3: /home size: 180.4 GiB used: 79.94 GiB (44.3%) fs: ext4 dev: /dev/nvme0n1p9
Swap:
  ID-1: swap-1 type: partition size: 16.76 GiB used: 1.8 MiB (0.0%) priority: -2
    dev: /dev/nvme0n1p8
Sensors:
  System Temperatures: cpu: 60.0 C pch: 61.0 C mobo: N/A gpu: nvidia temp: 55 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2825 apt: 2803 flatpak: 22
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirror.metanet.ch/linuxmint victoria main upstream import backport
    2: deb http: //ubuntu.ethz.ch/ubuntu jammy main restricted universe multiverse
    3: deb http: //ubuntu.ethz.ch/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //ubuntu.ethz.ch/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https: //updates.signal.org/desktop/apt xenial main
  Active apt repos in: /etc/apt/sources.list.d/slack.list
    1: deb https: //packagecloud.io/slacktechnologies/slack/debian/ jessie main
  No active apt repos in: /etc/apt/sources.list.d/steam-beta.list
  Active apt repos in: /etc/apt/sources.list.d/steam-stable.list
    1: deb [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https: //repo.steampowered.com/steam/ stable steam
    2: deb-src [arch=amd64,i386 signed-by=/usr/share/keyrings/steam.gpg] https: //repo.steampowered.com/steam/ stable steam
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
Info:
  Processes: 339 Uptime: 20m Memory: 15.46 GiB used: 5.3 GiB (34.2%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13
</pre>
</details> 

I can install and run Resources from the Software Manager, but the window shows no processes.
<image src="https://github.com/nokyan/resources/assets/74881094/cc804066-0c58-46ca-871c-3dadd5fb8e30" alt="a screenshot of the issue" />
If I run <code>flatpak run net.nokyan.Resources</code> I get this output showing a Rust error.
<pre>
flatpak run net.nokyan.Resources
 INFO  resources::application > Resources (net.nokyan.Resources)
 INFO  resources::application > Version: 1.0.3 ()
 INFO  resources::application > Datadir: /app/share/resources
 DEBUG resources::application::imp > GtkApplication<Application>::startup
 DEBUG resources::application::imp > GtkApplication<Application>::activate
thread 'main' panicked at src/ui/window.rs:209:71:
called `Result::unwrap()` on an `Err` value: IO error while reading marker: failed to fill whole buffer

Caused by:
    failed to fill whole buffer
stack backtrace:
   0:     0x55adae73d68c - <unknown>
   1:     0x55adae76b9bc - <unknown>
   2:     0x55adae73985e - <unknown>
   3:     0x55adae73d474 - <unknown>
   4:     0x55adae73ef03 - <unknown>
   5:     0x55adae73ec1c - <unknown>
   6:     0x55adae73f4f9 - <unknown>
   7:     0x55adae73f3f7 - <unknown>
   8:     0x55adae73dbb6 - <unknown>
   9:     0x55adae73f142 - <unknown>
  10:     0x55adae769673 - <unknown>
  11:     0x55adae769b6a - <unknown>
  12:     0x55adae539b58 - <unknown>
  13:     0x55adae528509 - <unknown>
  14:     0x55adae70aecd - <unknown>
  15:     0x55adae7086fb - <unknown>
  16:     0x7fcea981fd07 - <unknown>
  17:     0x7fcea9821e17 - <unknown>
  18:     0x7fcea98224d3 - g_main_context_iteration
  19:     0x7fcea9a05a4d - g_application_run
  20:     0x55adae4fa346 - <unknown>
  21:     0x55adae4fa446 - <unknown>
  22:     0x55adae588afc - <unknown>
  23:     0x55adae5734d7 - <unknown>
  24:     0x55adae441c23 - <unknown>
  25:     0x55adae441bf9 - <unknown>
  26:     0x55adae732bab - <unknown>
  27:     0x55adae441bec - <unknown>
  28:     0x7fcea8ac908a - <unknown>
  29:     0x7fcea8ac914b - __libc_start_main
  30:     0x55adae441ae5 - <unknown>
  31:                0x0 - <unknown>
  </pre>

**Comment by nokyan** [comment] 2023-10-13 22:52
I've just installed Linux Mint in a VM to try and it also doesn't work for me there. It seems like the small binary used to gather process info isn't allowed to find any. Very odd, I'll definitely look into this.

**Comment by ThinkerDreamer** [comment] 2023-10-13 22:55
Thanks a lot! I'm excited to try Resources. It looks very nice.

**Comment by ikaikahub** [comment] 2023-10-14 00:33
Same here. On latest debian 12 though

![Screenshot_2023-10-13_18-32-33](https://github.com/nokyan/resources/assets/124720971/affb11b5-224b-40bf-a955-07c3866e6a4f)

```
flatpak run net.nokyan.Resources
 INFO  resources::application > Resources (net.nokyan.Resources)
 INFO  resources::application > Version: 1.0.3 ()
 INFO  resources::application > Datadir: /app/share/resources
 DEBUG resources::application::imp > GtkApplication<Application>::startup
 DEBUG resources::application::imp > GtkApplication<Application>::activate
thread 'main' panicked at src/ui/window.rs:209:71:
called `Result::unwrap()` on an `Err` value: IO error while reading marker: failed to fill whole buffer

Caused by:
    failed to fill whole buffer
stack backtrace:
   0:     0x55ef1bfe768c - <unknown>
   1:     0x55ef1c0159bc - <unknown>
   2:     0x55ef1bfe385e - <unknown>
   3:     0x55ef1bfe7474 - <unknown>
   4:     0x55ef1bfe8f03 - <unknown>
   5:     0x55ef1bfe8c1c - <unknown>
   6:     0x55ef1bfe94f9 - <unknown>
   7:     0x55ef1bfe93f7 - <unknown>
   8:     0x55ef1bfe7bb6 - <unknown>
   9:     0x55ef1bfe9142 - <unknown>
  10:     0x55ef1c013673 - <unknown>
  11:     0x55ef1c013b6a - <unknown>
  12:     0x55ef1bde3b58 - <unknown>
  13:     0x55ef1bdd2509 - <unknown>
  14:     0x55ef1bfb4ecd - <unknown>
  15:     0x55ef1bfb26fb - <unknown>
  16:     0x7f2bf0864d07 - <unknown>
  17:     0x7f2bf0866e17 - <unknown>
  18:     0x7f2bf08674d3 - g_main_context_iteration
  19:     0x7f2bf0a4aa4d - g_application_run
  20:     0x55ef1bda4346 - <unknown>
  21:     0x55ef1bda4446 - <unknown>
  22:     0x55ef1be32afc - <unknown>
  23:     0x55ef1be1d4d7 - <unknown>
  24:     0x55ef1bcebc23 - <unknown>
  25:     0x55ef1bcebbf9 - <unknown>
  26:     0x55ef1bfdcbab - <unknown>
  27:     0x55ef1bcebbec - <unknown>
  28:     0x7f2befa3b08a - <unknown>
  29:     0x7f2befa3b14b - __libc_start_main
  30:     0x55ef1bcebae5 - <unknown>
  31:                0x0 - <unknown>
```

**Comment by chmurli** [comment] 2023-10-14 07:51
Same problem on up-to-date ArchLinux.

**Comment by nokyan** [comment] 2023-10-14 07:59
Thank you for all the reports, this will be the first thing I'll look into today.

**Comment by nokyan** [comment] 2023-10-14 12:59
Small update: I've fixed the bug that causes Resources to be completely blank and not load any other views when it's unable to see processes, it should now (i.e. hopefully later today or tomorrow when I release all the bugfixes) at least load the other stuff like CPU and memory. I could **not** yet find the cause for Resources to be unable to see processes in the first place on Linux Mint, Debian and Arch, especially since if I build and install Resources locally (in my Mint VM, I think this applies to Arch and Debian as well though) as a Flatpak, it works without issues.
I'm also working on better application detection since that was borked on Linux Mint as well.

**Comment by nokyan** [comment] 2023-10-14 16:13
Good news: I think I've found the issue!
The binary that gets spawned outside the flatpak and looks for processes linked to libadwaita on accident, which caused it to crash on systems without libadwaita (such as Linux Mint or Debian with Xfce). I didn't notice that because I use Fedora with GNOME which has libadwaita already installed. I will fix this issue and release Resources 1.1 either tonight or tomorrow (hopefully).
In the meantime, you should be able to fix this issue by installing libadwaita through your normal package manager, on Linux Mint and Debian that would be `sudo apt-get install libadwaita-1-0`. At least that fixed it for me in my Linux Mint VM. :)

**Comment by chmurli** [comment] 2023-10-14 17:45
Yes, installing libadwaita (via pacman of Arch) fixes a bug. But this should be in flatpak deps or something.

**Comment by Jack-Balcombe** [comment] 2023-10-14 19:14
Had this issue today when trying out Resources, too. Also on Linux Mint 21.2. Great to hear you found the issue, I might try out the app again later when I'm less busy

**Comment by nokyan** [comment] 2023-10-14 20:20
> Yes, installing libadwaita (via pacman on Arch) fixes a bug. But this should be in flatpak deps or something.

Yes, this will be fixed with Resources 1.1, should be released tonight or tomorrow. :)

**Closed** 2023-10-15 14:59 UTC

**Comment by ThinkerDreamer** [comment] 2023-10-16 11:10
Yes! I confirm on my (other) Mint 21.2 machine that Resources is now working and looking lovely. Thanks!

**Comment by Jack-Balcombe** [comment] 2023-10-16 18:08
It's now working on my computer too. Thanks!

**Comment by ikaikahub** [comment] 2023-10-17 22:47
Same works great. Love the app
