### ISSUE TITLE
[Feature] tree view for processes list

### ISSUE THREAD

**Issue by Ravenow** [nokyan/resources#101] opened 2023-11-23 10:07 UTC
It would be nice to have a way to toggle list/tree views in processes tab

**Comment by nokyan** [comment] 2023-11-23 17:36
Hi, thank you for the feature suggestion. I believe this is a duplicate of #47, so I'll close this one. If I'm wrong, don't hesitate to reopen. :)

**Closed by nokyan** 2023-11-23 17:36 UTC
