### ISSUE TITLE
[Request feature] Hierarchy structure for Processes

### ISSUE THREAD

**Issue by Sethox** [nokyan/resources#407] opened 2024-11-30 13:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

It's simple really, as the title suggest, I want a hierarchy processes option to line up the processes by sub-process to their parent processes.

### Additional context

Doesn't happen often, but if a parent processes is killed, it may happen that a sub-processes may end up a zombie, I have a habit to kill the entire tree for said process so it doesn't happen. It's a minor feature, but it gives visual clarification about process information.

**Comment by nokyan** [comment] 2024-11-30 17:28
Hi, thanks for the issue.
I believe this is a duplicate of https://github.com/nokyan/resources/issues/47, so I'll close this one. If I'm wrong, don't hesitate to reopen. :)
I'll try to make it happen for Resources 1.8.

**Closed** 2024-11-30 17:36 UTC
Labels: enhancement
