### ISSUE TITLE
Support for NPU devices

### ISSUE THREAD

**Issue by adrianboguszewski** [nokyan/resources#302] opened 2024-07-22 13:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the solution you'd like

Many modern CPUs e.g. Intel Core Ultra 7 155H include integrated NPUs (Neural Processing Units). It would be nice to display the utilization of these devices in Resources like in Windows Task Manager.

### Additional context

![image](https://github.com/user-attachments/assets/80faa2a1-a080-492b-a8d5-4455a787ede2)

**Comment by adrianboguszewski** [comment] 2024-07-23 11:03
@nokyan Oh, you're right, changed :)

@jwludzik do we expose that kind of information (e.g. utilization) in the driver?

**Comment by adrianboguszewski** [comment] 2024-07-23 18:23
Linux NPU driver repo: https://github.com/intel/linux-npu-driver

**Comment by m-falkowski** [comment] 2024-07-26 14:59
Hello @adrianboguszewski @nokyan,

I am going to prepare an example how to measure NPU utilization for next week.

**Comment by m-falkowski** [comment] 2024-08-12 15:32
Hi @adrianboguszewski @nokyan,
 
NPU utilization may be calculated using device's sysfs file `npu_busy_time_us` that contains the time that the device spent executing jobs. NPU is considered 'busy' starting with a first job submitted to firmware and ending when there is no more jobs pending/executing.
 
To measure an utilization either calculate from `npu_busy_time_us` difference delta to see NPU active duration during workload or monitor utilization percentage by reading npu_busy_time_us periodically.
 
You may see the commit introducing this feature: [accel/ivpu: Share NPU busy time in sysfs](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/accel/ivpu?h=next-20240812&id=0adff3b0ef12483a79dc8415b94547853d26d1f3)
 
This is a sample Bash code that should showcase a usage of utilization:
 
 ```bash
NPU_BUSY_TIME_PATH="/sys/devices/pci0000:00/0000:00:0b.0/npu_busy_time_us"
TIME_1=$(cat "$NPU_BUSY_TIME_PATH")
while true; do
  sleep "$SAMPLING_PERIOD"
  TIME_2=$(cat "$NPU_BUSY_TIME_PATH")
  clear
  DELTA=$(("$TIME_2" - "$TIME_1"))
  echo "NPU busy time: $TIME_2 us"
  echo "NPU busy time delta: $DELTA us"
  echo "NPU Utilization: $(( 100 * "$DELTA" / "$SAMPLING_PERIOD" / 1000000 ))%"
  TIME_1=$TIME_2
done
```

**Comment by nokyan** [comment] 2024-08-12 16:33
@m-falkowski Thanks a lot! I'm afraid NPU support won't make it in Resources 1.6 though which will be released in about two weeks. I'll start implementing it after the release. :)

**Comment by nokyan** [comment] 2024-10-10 18:08
Hi there, I've finally gotten around to implementing NPU support. Do you mind checking out the [`npu`](https://github.com/nokyan/resources/tree/npu) branch and see if it works?

**Comment by m-falkowski** [comment] 2024-10-18 16:00
> Hi there, I've finally gotten around to implementing NPU support. Do you mind checking out the [`npu`](https://github.com/nokyan/resources/tree/npu) branch and see if it works?

Hi @nokyan ,

Thank you for this change!
I tested it and it works reliably but calculates the percentage utilization incorrectly.
The utilization was not scaled so it was shown it thousands of percents.

https://github.com/nokyan/resources/blob/npu/src/utils/npu/intel.rs#L67-L82

```rust
    fn usage(&self) -> Result<f64> {
        let last_timestamp = self.last_busy_time_timestamp.get();
        let last_busy_time = self.last_busy_time_us.get();

        let new_timestamp = unix_as_millis();
        let new_busy_time = self
            .read_device_int("npu_busy_time_us")
            .map(|int| int as usize)?;

        self.last_busy_time_timestamp.set(new_timestamp);
        self.last_busy_time_us.set(new_busy_time);

        let delta_timestamp = new_timestamp.saturating_sub(last_timestamp) as f64;
        let delta_busy_time = new_busy_time.saturating_sub(last_busy_time) as f64;

        Ok(delta_busy_time / delta_timestamp)
    }
```

Changing the last division into ` Ok((delta_busy_time / delta_timestamp) / 1000.0)` resolves the issue and utilization as shown below:

![utilization](https://github.com/user-attachments/assets/91e58f5c-4dca-47ff-91ee-e0d0291deeea)

**Comment by nokyan** [comment] 2024-10-18 16:43
> > Hi there, I've finally gotten around to implementing NPU support. Do you mind checking out the [`npu`](https://github.com/nokyan/resources/tree/npu) branch and see if it works?
> 
> Hi @nokyan ,
> 
> Thank you for this change! I tested it and it works reliably but calculates the percentage utilization incorrectly. The utilization was not scaled so it was shown it thousands of percents.
> 
> https://github.com/nokyan/resources/blob/npu/src/utils/npu/intel.rs#L67-L82
> 
> ```rust
>     fn usage(&self) -> Result<f64> {
>         let last_timestamp = self.last_busy_time_timestamp.get();
>         let last_busy_time = self.last_busy_time_us.get();
> 
>         let new_timestamp = unix_as_millis();
>         let new_busy_time = self
>             .read_device_int("npu_busy_time_us")
>             .map(|int| int as usize)?;
> 
>         self.last_busy_time_timestamp.set(new_timestamp);
>         self.last_busy_time_us.set(new_busy_time);
> 
>         let delta_timestamp = new_timestamp.saturating_sub(last_timestamp) as f64;
>         let delta_busy_time = new_busy_time.saturating_sub(last_busy_time) as f64;
> 
>         Ok(delta_busy_time / delta_timestamp)
>     }
> ```
> 
> Changing the last division into ` Ok((delta_busy_time / delta_timestamp) / 1000.0)` resolves the issue and utilization as shown below:
> 
> ![utilization](https://private-user-images.githubusercontent.com/37086824/377935573-91e58f5c-4dca-47ff-91ee-e0d0291deeea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjk1MjUsIm5iZiI6MTcyOTI2OTIyNSwicGF0aCI6Ii8zNzA4NjgyNC8zNzc5MzU1NzMtOTFlNThmNWMtNGRjYS00N2ZmLTkxZWUtZTBkMDI5MWRlZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE2MzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZmRkNWQxYzEwNTFkNDc2MjU4NmYzNmYwMTU2YWZhZjA4NjY0NzlhNTM1ZjE4YWFmNmY2NGZlYWI0NTE4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nGnJ7gV308v1ON_MPc-AITqI7SO_tvDYS3PGHMD3p_k)

Looks good! I'll fix that soon. Unfortunately the driver doesn't seem to expose anything but the compute utilization, no memory usage or frequencies yet. :/

**Closed** 2024-10-19 05:19 UTC
Labels: enhancement

**Comment by adrianboguszewski** [comment] 2024-10-23 12:29
@nokyan I'm happy to see that :) When can we expect the next release with this feature on the board?

**Comment by nokyan** [comment] 2024-10-23 12:39
> @nokyan I'm happy to see that :) When can we expect the next release with this feature on the board?

I plan to release 1.7 with NPU support probably on 29 November :)

**Comment by Martin-HZK** [comment] 2024-10-25 12:55
> > Hi there, I've finally gotten around to implementing NPU support. Do you mind checking out the [`npu`](https://github.com/nokyan/resources/tree/npu) branch and see if it works?
> 
> Hi @nokyan ,
> 
> Thank you for this change! I tested it and it works reliably but calculates the percentage utilization incorrectly. The utilization was not scaled so it was shown it thousands of percents.
> 
> https://github.com/nokyan/resources/blob/npu/src/utils/npu/intel.rs#L67-L82
> 
> ```rust
>     fn usage(&self) -> Result<f64> {
>         let last_timestamp = self.last_busy_time_timestamp.get();
>         let last_busy_time = self.last_busy_time_us.get();
> 
>         let new_timestamp = unix_as_millis();
>         let new_busy_time = self
>             .read_device_int("npu_busy_time_us")
>             .map(|int| int as usize)?;
> 
>         self.last_busy_time_timestamp.set(new_timestamp);
>         self.last_busy_time_us.set(new_busy_time);
> 
>         let delta_timestamp = new_timestamp.saturating_sub(last_timestamp) as f64;
>         let delta_busy_time = new_busy_time.saturating_sub(last_busy_time) as f64;
> 
>         Ok(delta_busy_time / delta_timestamp)
>     }
> ```
> 
> Changing the last division into ` Ok((delta_busy_time / delta_timestamp) / 1000.0)` resolves the issue and utilization as shown below:
> 
> ![utilization](https://private-user-images.githubusercontent.com/37086824/377935573-91e58f5c-4dca-47ff-91ee-e0d0291deeea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjExNjIsIm5iZiI6MTcyOTg2MDg2MiwicGF0aCI6Ii8zNzA4NjgyNC8zNzc5MzU1NzMtOTFlNThmNWMtNGRjYS00N2ZmLTkxZWUtZTBkMDI5MWRlZWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEyNTQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZDg3MDgwNmI1NTI5MWI3ZWJhZTFhOGEzODY2NDMzNzA2MWRjOGViZTQ5MDJhNGY4ODgyMzlkZDMxYzRmOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.645-_dkhRGL2XFUpB0I8qW9w44ZhDCsgQYbyIjWWkz8)

How can we have the NPU listed in the performance layout? My Ubuntu 24.04 does not even identify the device

**Comment by nokyan** [comment] 2024-10-25 13:00
> How can we have the NPU listed in the performance layout? My Ubuntu 24.04 does not even identify the device

I can't help you without any information.
What NPU do you have?
Are you trying out the latest commit on GitHub or the current release on Flathub? The current release on Flathub doesn't have this feature yet, it will be included with the next release.
What kernel do you currently use? Please send me the output of `uname -a` in your terminal.

**Comment by Martin-HZK** [comment] 2024-10-25 13:06
> > How can we have the NPU listed in the performance layout? My Ubuntu 24.04 does not even identify the device
> 
> I can't help you without any information. What NPU do you have? Are you trying out the latest commit on GitHub or the current release on Flathub? The current release on Flathub doesn't have this feature yet, it will be included with the next release. What kernel do you currently use? Please send me the output of `uname -a` in your terminal.

Thank you for your timely reply! The detailed system information are as follows:

Currently I am using Intel Corporation Meteor Lake NPU and the driver I installed is [Linux NPU Driver v1.8.0](https://github.com/intel/linux-npu-driver/releases/tag/v1.8.0) presented for release on GitHub. The OS I installed is Ubuntu 24.04 LTS

``` shell
$ uname -a
Linux hzk-Martin 6.8.1+ #2 SMP PREEMPT_DYNAMIC Thu Oct 24 18:31:43 CST 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nokyan** [comment] 2024-10-25 13:09
Are you using the current production release of Resources on Flathub or are you building and using the latest commit from GitHub?

**Comment by Martin-HZK** [comment] 2024-10-25 13:10
> Are you using the current production release of Resources on Flathub or are you building and using the latest commit from GitHub?

I have strictly adhere to the installation guideline on GitHub with its corresponding release version

**Comment by nokyan** [comment] 2024-10-25 13:28
Could you run Resources from your terminal with the environment variable `RUST_LOG=resources=debug` set and send me the output?

**Comment by Martin-HZK** [comment] 2024-10-25 13:36
Sry for my mistake. Currently the exact 'Resources' application is downloaded from Flatpak.

**Comment by nokyan** [comment] 2024-10-25 13:56
> Sry for my mistake. Currently the exact 'Resources' application is downloaded from Flatpak.

Thanks, no worries. The current release of Resources on Flathub does not have the NPU feature yet.

**Comment by Martin-HZK** [comment] 2024-10-25 14:35
> > Sry for my mistake. Currently the exact 'Resources' application is downloaded from Flatpak.
> 
> Thanks, no worries. The current release of Resources on Flathub does not have the NPU feature yet.

So does any of the releases in GitHub support NPU? I didn't see any of the releases mentions NPU. Or which commit hash code will you recommend for NPU profiling?

**Comment by nokyan** [comment] 2024-10-25 15:32
> > > Sry for my mistake. Currently the exact 'Resources' application is downloaded from Flatpak.
> > 
> > 
> > Thanks, no worries. The current release of Resources on Flathub does not have the NPU feature yet.
> 
> So does any of the releases in GitHub support NPU? I didn't see any of the releases mentions NPU. Or which commit hash code will you recommend for NPU profiling?

The NPU support is already in the main branch, just not in a production release yet. The branch for NPU support has been merged in commit `5583d7d64d6b0f8d4ee0a5b639505a887341b462`. In the README you can find instructions on how to build the latest commit of Resources yourself. It boils down to cloning the repo and running this in your terminal while being in the repo's root:
```sh
flatpak install org.gnome.Sdk//47 org.freedesktop.Sdk.Extension.rust-stable//24.08 org.gnome.Platform//47 org.freedesktop.Sdk.Extension.llvm18//24.08
flatpak-builder --user flatpak_app build-aux/net.nokyan.Resources.Devel.json
flatpak-builder --run flatpak_app build-aux/net.nokyan.Resources.Devel.json resources
```
Release 1.7, which will ship NPU support, will release most likely on 29 November to Flathub and of course will also get a GitHub tag and release.

**Comment by Martin-HZK** [comment] 2024-10-25 16:27
> > > > Sry for my mistake. Currently the exact 'Resources' application is downloaded from Flatpak.
> > > 
> > > 
> > > Thanks, no worries. The current release of Resources on Flathub does not have the NPU feature yet.
> > 
> > 
> > So does any of the releases in GitHub support NPU? I didn't see any of the releases mentions NPU. Or which commit hash code will you recommend for NPU profiling?
> 
> The NPU support is already in the main branch, just not in a production release yet. The branch for NPU support has been merged in commit `5583d7d64d6b0f8d4ee0a5b639505a887341b462`. In the README you can find instructions on how to build the latest commit of Resources yourself. It boils down to cloning the repo and running this in your terminal while being in the repo's root:
> 
> ```shell
> flatpak install org.gnome.Sdk//47 org.freedesktop.Sdk.Extension.rust-stable//24.08 org.gnome.Platform//47 org.freedesktop.Sdk.Extension.llvm18//24.08
> flatpak-builder --user flatpak_app build-aux/net.nokyan.Resources.Devel.json
> flatpak-builder --run flatpak_app build-aux/net.nokyan.Resources.Devel.json resources
> ```
> 
> Release 1.7, which will ship NPU support, will release most likely on 29 November to Flathub and of course will also get a GitHub tag and release.

The newest commit returns result like this:

![image](https://github.com/user-attachments/assets/02b6d393-f725-4b93-be35-c17513a2d271)


Why does this happened? It seems that the NPU info is not successfully collected for commit 215dd36

**Comment by nokyan** [comment] 2024-10-25 16:43
You are running Linux 6.8, which I believe does not contain the support for the sysfs interface that allows Resources to track usage for Intel NPUs. You could try updating your kernel. It could also be that Ubuntu 24.04 just does not offer kernel that's new enough for this feature. In this case, you could either try upgrading to Ubuntu 24.10 or try to manually install a newer kernel, though the latter can be risky if you're not experienced with that.

**Comment by Martin-HZK** [comment] 2024-10-25 16:50
Does that mean I cannot even access the NPU services with rebuilding the current linux kernel?

**Comment by jwludzik** [comment] 2024-10-25 17:58
Yes. The Ubuntu releases is fixed to kernel version, see "Kernel release schedule
" in https://ubuntu.com/kernel/lifecycle. The NPU utilization solution used in nokyan/resource (many thanks to @nokyan) utilize the patch [0adff3b0ef12483a79dc8415b94547853d26d1f3](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/accel/ivpu?h=next-20240812&id=0adff3b0ef12483a79dc8415b94547853d26d1f3) that has been merged to Linux kernel **v6.11**. I am sorry for the inconvenience. The main recommendation is to use Ubuntu 24.10 as @nokyan mentioned previously

**Comment by Martin-HZK** [comment] 2024-10-25 18:06
Thank you for your clarification. While I have been carrying out my experiment with other parts running successfully, is it enough for me to simply upgrade the kernel for convenience?

**Comment by Martin-HZK** [comment] 2024-10-26 03:14
> Yes. The Ubuntu releases is fixed to kernel version, see "Kernel release schedule " in https://ubuntu.com/kernel/lifecycle. The NPU utilization solution used in nokyan/resource (many thanks to @nokyan) utilize the patch [0adff3b0ef12483a79dc8415b94547853d26d1f3](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/accel/ivpu?h=next-20240812&id=0adff3b0ef12483a79dc8415b94547853d26d1f3) that has been merged to Linux kernel **v6.11**. I am sorry for the inconvenience. The main recommendation is to use Ubuntu 24.10 as @nokyan mentioned previously

Thank you for your advice! The problem is solved with upgrading the kernel version to 6.11

**Comment by adrianboguszewski** [comment] 2024-10-30 13:45
Wow! It looks super cool!
![Screenshot From 2024-10-30 14-43-51](https://github.com/user-attachments/assets/0109e6b1-2990-4ee2-825d-ab7d66b7253e)
Thanks, @nokyan for implementing that!

**Comment by nokyan** [comment] 2024-10-30 15:34
> Wow! It looks super cool! ![Screenshot From 2024-10-30 14-43-51](https://private-user-images.githubusercontent.com/4547501/381575582-0109e6b1-2990-4ee2-825d-ab7d66b7253e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDI3MjcsIm5iZiI6MTczMDMwMjQyNywicGF0aCI6Ii80NTQ3NTAxLzM4MTU3NTU4Mi0wMTA5ZTZiMS0yOTkwLTRlZTItODI1ZC1hYjdkNjZiNzI1M2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMzBUMTUzMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ0Nzc3MmI0N2Q5MzViM2FkYjc1MmNmNzIwMTc1ZTdiMTFkODZmMzYwMWU2ZWEzYzhmNWMwZGQyOWUwZWQ0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.a9_Di_kYCjz4gv_0J9wIH39zLy8CY3s1h7ulsh9gEh8) Thanks, @nokyan for implementing that!

I'm glad you like it!
